let num = [5,8,4,1]

console.log(`Nosso vetor: ${num}`)
console.log('======================================')
console.log('')
console.log(`Ele tem um comprimento de ${num.length} posições.`)
console.log(`Vou criar mais um elemento na posição de chave 4.`)
num[4] = 9
console.log('')
console.log('======================================')
console.log(`Nosso vetor: ${num}`)
console.log('======================================')
console.log('')
console.log(`Vou criar um elemento com o valor "7" na última posição.`)
num.push(7)
console.log('')
console.log('======================================')
console.log(`Nosso vetor: ${num}`)
console.log('======================================')
console.log('')
console.log(`Vamos ordenar ele do maior para o menor.`)
num.sort()
console.log('')
console.log('======================================')
console.log(`Nosso vetor: ${num}`)
console.log('======================================')